### ISSUE TITLE
Warning message for Too few reads (0) usable for estimating error and conversion rates

### ISSUE THREAD

**Issue by Codezy99** [erhard-lab/gedi#64]
Hello, 

I met a problem when I run the GRAND-Slam for my SLAM-seq data. For some of my samples, the tool report a warning message which said:
`WARNING Too few reads (0) usable for estimating error and conversion rates; maybe your experiments did not work. To circumvent this warning, invoke with smaller -minEstimateReads or specify rates directly via -conv/-err!`

But actually there are about 14.7% of reads containning at least one T to C transition in that sample. I was wondering whether you know any potantial reason for this warning message and how can I fix this. 

Here are the parameter that I use for mapping and run the GRAND-Slam:
`STAR --runThreadN 16 --genomeDir xxx --readFilesIn $i --outFileNamePrefix $i --outSAMtype BAM SortedByCoordinate --outFilterMultimapNmax 10 --alignEndsType EndToEnd --outSAMattributes MD NH`

`gedi -e Slam -genomic /home/.gedi/genomic/SC_105.oml -errlm TA*1.434 -trim5p 3 -trim3p 3 -prefix $i -progress -plot -D -minEstimateReads 1000 -reads $i`
 
Thank you!

Best,
You Zhou

**Comment by florianerhard** [comment]
Dear You Zhou,
there might be several reasons for this. grand-slam tries to find reads for which it is safe to assume that they originate from new RNA. Only these reads are then used to estimate the incorporation frequency of 4sU. It is safe to assume this if there are so many T>C mismatches in the read that is is extremely unlikely that they are all due to sequencing errors. For that, grand-slam first estimates the sequencing error rate p_e and then makes use of this to estimate this probability.

The warning message means that it did not find a single read "(0)" for estimating the incorporation frequency. This could either mean that p_e is way too high (you are using TA*1.434; do you also see a lot of T>A mismatches?), or that your reads are too short (such that 15% might have a T>C mismatch, but there are indeed no reads with more than, let's say, 2 mismatches.

Also, you apparently are running grandslam on a single bam file, right? If you have several samples (preferrably also including 4sU naive controls), you should combine the bam files into a single cit file and run grandslam on this!

Best,
Florian

**Comment by Codezy99** [comment]
In the end, I use an early time point as no4sU control and partially fix this problem.

**Comment by aishwarya-gondane** [comment]
Hi,

I have encountered similar warnings and the results from this analysis cannot be used to deduce the log fold change or the significance. I have combined all my samples in a single cit file, however, my BAM files are aligned using Bowtie. Can I use these files or should I make BAM files using STAR?

**Comment by florianerhard** [comment]
We have never tested BAM files generated by bowtie. We recommend using STAR.
